theme: jekyll-theme-cayman
title: BagIt-ENabled Deposit (BAGEND)
description: Provides a publication-centric model for describing BagIt payloads
show_downloads: false

defaults:
    - 
        scope:
            path: "bagit-profile/0.1"
        values:
            layout: null
            permalink: /bagit-profile/0.1
