#!/bin/bash

for ip in 185.199.109.153 185.199.111.153 185.199.108.153 185.199.110.153 ;
do
  curl -s -o /dev/null -w "%{http_code} %{content_type}" -H "Host: bagend.io" http://$ip/bagit-profile/0.1
  echo ""
done
